apiVersion: v1
kind: Pod
metadata:
  name: "{{.Release.Name}}-expect-to-fail"
  annotations:
    "helm.sh/hook": test-failure
spec:
  containers:
    - name: "{{.Release.Name}}-smoke-test"
      image: "busybox"
      command: ["false"]
  restartPolicy: Never